# Generated by Django 5.2 on 2025-06-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheBrew', '0003_pointrequest_image_pointrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointrequest',
            old_name='profile',
            new_name='account',
        ),
    ]
