# Generated by Django 5.2 on 2025-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBrew', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('diamond', 'Diamond')], default='everyone')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expired_date', models.DateField()),
            ],
        ),
    ]
