# Generated by Django 5.2 on 2025-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBrew', '0007_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateField(),
        ),
    ]
